spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/tasklist?currentSchema=tasklist
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      continue-on-error: false
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
security:
  jwt:
    secret: ZmRqc2pma3NkbmprZnNrbGxmc2Zkc2Zkcw==
    access: 3600000
    refresh: 2592000000
logging:
  level:
    org.springframework.security: trace


#      data-locations: classpath:demo_data.sql
