spring:
  cache:
    type: redis
    cache-names: redis-cache
  data:
    redis:
      host: localhost
      port: 6379
      password: amZqcGlpdXl5ZHNuZm5zcXZkcw==
  datasource:
    url: jdbc:postgresql://localhost:5433/tasklist?currentSchema=tasklist
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
      continue-on-error: false
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: tasklist
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
security:
  jwt:
    secret: ZmRqc2pma3NkbmprZnNrbGxmc2Zkc2Zkcw==
    access: 3600000
    refresh: 2592000000
logging:
  level:
    org.springframework.security: trace
springdoc:
  override-with-generic-response: false


#      data-locations: classpath:demo_data.sql
